### ISSUE TITLE
Mouse cursor size in between containers

### ISSUE THREAD

**Issue by trmendes** [swaywm/sway#3014]
```
swaymsg version 1.0-beta.1-93-ge3a0e3322b4f (Oct 27 2018, branch 'master')
```

I have a sway output configured to scale 2 and gapps on

```
....
# GAPS CONFIG
smart_gaps on
gaps inner 1
gaps outer 1
....
# LAPTOP DISPLAY
output $output_main {
    scale 1.8
    background "$HOME/Pictures/wallpapers/moonlit.jpg" fill
}
...
```

When I'm moving the mouse cursor around the containers I see that when I'm in between two containers the mouse cursor get twice the size it has when it is over a container window.

**Comment by Ferdi265** [comment]
I think this is caused by the fact that on Wayland, drawing the mouse cursor is left up to the application. So in this case, your applications don't seem to agree on the scale of the mouse cursor. See #330.

**Comment by emersion** [comment]
Yeah, it's probably due to that. Note that fixing this issue is a work-in-progress, see https://github.com/swaywm/wlroots/pull/1324

**Comment by emersion** [comment]
I think this has been fixed, at least for the Sway cursors. For client cursors, we set `XCURSOR_SIZE` in the env.

**Comment by q234rty** [comment]
I can still reproduce this on sway/wlroots master with scale 1.75 and cursor size `24`
