### ISSUE TITLE
swayidle before-sleep only works once

### ISSUE THREAD

**Issue by electrickite** [swaywm/sway#3062]
I have the following `swayidle` command in my sway config:

    exec swayidle \
        timeout 300 'swaylock -c 000000' \
        timeout 600 'swaymsg "output * dpms off"' \
          resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock -c 000000'

As expected, the first time I trigger system sleep, ie. with `systemctl suspend`, the screen is locked prior to suspend and I am forced to enter a password on resume.

However, after resuming, if I trigger another suspend the screen is not locked and I am not prompted for my password on the next resume.

This behavior occurs for both suspend and hibernate. It appears as if the before-sleep command is only being run the first time the system sleeps.

sway version 1.0-beta.1-138-gd19648a3 (Nov  4 2018, branch 'master')

**Comment by emersion** [comment]
Fixed by https://github.com/swaywm/sway/pull/3049, probably

**Comment by ggreer** [comment]
#3049 fixed this issue for me, though now `before-sleep` happens after resume. After I wake up my laptop, there's a fraction of a second where my screen is unlocked. #3198 sorta describes what I'm seeing.

**Comment by tokyovigilante** [comment]
I often get a flash of the previous (unlocked) screen content before seeing the lock screen when I wake my laptop from sleep too. Standard Fedora 29/systemd and the config above.

**Comment by akiva** [comment]
Following here, rather than #3198. Just to confirm, running latest build on Arch, opening the lid for the first time runs `swaylock` as expected. After that, it fails to get triggered. No flash or anything, as some have reported, just the plain, unlocked desktop.

**Comment by electrickite** [comment]
It seems that #3049 fixed the issue for me, but leaving the issue open for now since other issues are being discussed.

**Comment by emersion** [comment]
Maybe fixed by https://github.com/swaywm/sway/pull/3381?

**Comment by electrickite** [comment]
@emersion The original issue was fixed by #3049, at least for me.

**Comment by emersion** [comment]
The remaining issue is a duplicate of https://github.com/swaywm/sway/issues/3119

**Comment by gnzlbg** [comment]
This is not fixed for me. swayidle before-sleep only works once

**Comment by akiva** [comment]
Agreed, this still does not work for me. I have tried every suggestion from each of the linked bugs. 

`~/.config/sway/config.d/idle`:
```sh
exec swayidle -w \
  timeout 120 'swaylock -f -c 000000' \
  timeout 600  'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"' \
  before-sleep 'swaylock -f -c 000000'
```

and, yes, `~/.config/sway/config` sources that file, amongst others: `include config.d/*`

**Comment by emanuelserpa** [comment]
not working for me too.

**Comment by rlad78** [comment]
I found a workaround that works well for me that I thought I'd share. Found it through one of the issues at the swaylock repo (involves systemd just fyi): https://github.com/swaywm/swaylock/issues/41

There's a section in the Sway wiki about [Systemd integration](https://github.com/swaywm/sway/wiki/Systemd-integration) that you can read through, but here's what I gathered from it.

Create the following files in either `~/.config/systemd/user/` (single user)
OR `/etc/systemd/user/` for all users.

`sway-session.target`:
```
[Unit]
Description=sway compositor session
Documentation=man:systemd.special(7)
BindsTo=graphical-session.target
Wants=graphical-session-pre.target
After=graphical-session-pre.target
```

`swayidle.service`:
```
[Unit]
Description=Idle manager for Wayland
Documentation=man:swayidle(1)
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/swayidle -w \
            timeout 300 'swaylock -f -c 000000' \
            timeout 600 'swaymsg "output * dpms off"' \
                resume 'swaymsg "output * dpms on"' \
            before-sleep 'swaylock -f -c 000000'
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sway-session.target
```

Then, add this to the bottom of your sway config:
```
exec "systemctl --user import-environment; systemctl --user start sway-session.target"
```

And enable your swayidle service:
```
systemctl --user enable --now swayidle.serivce
```

If you get stuck on any one of these, or need some more understanding, I highly recommend reading through the linked issue and wiki article.
