### ISSUE TITLE
Mouse cursor not scaling correctly over swaybar and swaybg

### ISSUE THREAD

**Issue by johnae** [swaywm/sway#4112]
sway version c1186182785d15eb205bac4b49d0888e1a6601ee
wlroots version cf3b083c329b4e3ce89d16d77253e30137e86da2

```
swaymsg -t get_outputs
Output eDP-1 'Sharp Corporation 0x148B 0x00000000' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 2.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3: term
  Available modes:
    3840x2160 @ 47.997002 Hz
    3840x2160 @ 59.997002 Hz
```

Basically the cursor looks good over applications, but when over just swaybg or swaybar it is very small (as if it wasn't scaled I suppose).

**Comment by naibaf0** [comment]
This has been a work in progress for a while, see here: https://github.com/swaywm/wlroots/pull/1324

Also see #3014 and a few more.

**Comment by johnae** [comment]
Ok. Odd, I just seem to remember it not doing this when over swaybg / swaybar just a month ago or something. Perhaps it's always been a thing as you say though.

**Comment by ianyfan** [comment]
Ref https://github.com/swaywm/sway/issues/1750

**Comment by nostdm** [comment]
Same issue here, it used to scale fine, now it's small when hovering over tabs, background and swaybar.

**Comment by heroin-moose** [comment]
I have the following debug message when I move cursor over swaybg or sway titlebars

```
00:04:09.454 [sway/input/cursor.c:773] denying request to set cursor from unfocused client
```

If I remove the relevant check cursor gets consistent with xcursor theme and size but it glitches like crazy on every move. I don't know if this code path is relevant, just and observation.

**Comment by tv42** [comment]
For me, this got fixed by applying the config from https://github.com/swaywm/sway/issues/6931 and explicitly setting the cursor theme:

```
seat seat0 xcursor_theme Adwaita
```

**Comment by Zeioth** [comment]
I can confirm the xcursor theme matters. On my end the cursor Breeze only scales correctly on X apps, while Adwaita seems to scale correctly on all applications.

**Comment by xi-pinmping** [comment]
This is still an issue for me with swaybg but nothing else so far
