### ISSUE TITLE
non resizable applications can be resized

### ISSUE THREAD

**Issue by markand** [swaywm/sway#4710]
Hi,

I have written a game using SDL 2 and another one with SFML and both are non-resizable. On Xfce it is not possible to resize them however on sway 1.2 I get the following behavior:

- SDL use the wayland backend and starts as tiled immediately, it can be resized.
- SFML does not have wayland backend and use XWayland, it starts floating and can be resized.

I saw there was the issue #1672 but it was closed without any information so I can't find/understand what is the current expectation and support for them?

In my opinion, SFML app does the good thing of starting floating but both windows should not be resized. While asking, I remember that mpv/mplayer have some resize hints to keep their aspect ratio it looks like in sway it is also not honored (I can break the video ratio) but this is a lesser issue since mpv adds a letter box into its frame.

I have looked into existing issues but did not find anything related or if I missed it I apologize in advance.

**Comment by ascent12** [comment]
Can you look at `WAYLAND_DEBUG=1` log for your program?
We use `xdg_toplevel.set_max_size` and `xdg_toplevel.set_min_size` to determine if a client is resizeable or not.

**Comment by markand** [comment]
Thanks for the answer.

Here are the logs:

http://markand.fr/static/sfml.txt (check for "Save the ball" which is the SFML app once started)
http://markand.fr/static/sdl.txt (check for "Game" which is similar but for SDL).

Also, I've noticed that SDL starts floating if using xwayland, by *not* specifying `SDL_BACKEND=wayland` (it still uses X11 by default if unset).

**Comment by kennylevinsen** [comment]
In that log, there is only a single case of min/max being set, which is actually a protocol violation as it is setting max_size < min_size. Max size must be larger than or equal to min size if set, and thus to be non-resizable, min_size must be equal to max_size.

However, I'm not sure if it's the game surface this is called on. You seem to have logged a lot of things to that log, instead of just that single application. Please redo the WAYLAND_DEBUG log like so:

```shell
WAYLAND_DEBUG=1 your-application 2> wayland-debug.log
```

The log will only contain protocol information from that single application. Do not set WAYLAND_DEBUG globally.

**Comment by markand** [comment]
Thanks for the reply. So let's start with the SDL2 issue which is a native wayland application. Here's the log with WAYLAND_DEBUG=1 only for the SDL2 application:

http://markand.fr/static/sdl-2.txt

**Comment by kennylevinsen** [comment]
This log shows that min/max size is never set. In other words, SDL2 is never asking for any type of size constraint, which is why the window is a resizable tile rather than a fixed-size floating window.

The issue is either in SDL2 or in your game, although I'll place my bet on SDL2's wayland backend just not implementing size constraints.

**Comment by markand** [comment]
That's strange because on GNOME the window is not resizable, so I wonder how GNOME detect this :(

**Comment by kennylevinsen** [comment]
Are you sure you tested GNOME Wayland with SDL2's Wayland backend? If so, does the same log made on GNOME contain the min/max calls?

That is the only way to constrain a toplevel window after all.

**Comment by markand** [comment]
Indeed, I have a global `SDL_VIDEODRIVER=wayland` set. I also immediately know that it's running under wayland because it is scaled while it isn't under GNOME's X session.

What I've found interesting though, is that GNOME offers a “Resize” option in the window menu (the option is greyed out if running under X) when the SDL application is running under wayland but the window is *still* not resizable (so it looks like it also think the window can be resized). No matter what I do with the mouse or keyboard shortcut, I still can't resize it.

The log while running under GNOME: http://markand.fr/static/sdl-gnome.txt

**Comment by kennylevinsen** [comment]
I see no min/max size in the log here either, which means that size constraints are not correctly implemented.

I'd place my bet on SDL2 just ignoring resize requests. This means that the compositor is entirely unaware of size constraints, and presents the window as resizable. However, attempts to resize will just be ignored (on a tiling compositor like Sway, the tile till resize but content remains fixed, while a windowed compositor will just not budge despite making it seem like it should).

Not knowing neither SDL2 nor your code, I cannot rule out that you are simply using SDL2 wrong with regards to size constraints, but assuming everything is good on your end, then the issue is in SDL2. Sway and GNOME are both doing the right thing, and SDL2 if used correctly must emit min/max size calls where current_size = min_size = max_size.

**Comment by markand** [comment]
Thanks for your time. for the SDL wayland backend I'll open an issue to their bugtracker with a link pointing to this one.

Note, a simple code snippet to demonstrate the non-resizable window can be used:

```cpp
#include <SDL.h>

int main(int, char**)
{
	SDL_Window* win;
	SDL_Renderer* renderer;

	SDL_Init(SDL_INIT_VIDEO);
	win = SDL_CreateWindow("test", 0, 0, 500, 500, 0); // not resizable
	renderer = SDL_CreateRenderer(win, -1, 0);

	for (;;) {
		SDL_Event ev;
		while (SDL_PollEvent(&ev)) {
			switch (ev.type) {
			case SDL_QUIT:
				return 0;
			default:
				break;
			}
		}

		SDL_RenderClear(renderer);
		SDL_RenderPresent(renderer);
		SDL_Delay(20);
	}

	return 0;
}
```

(Don't forget `SDL_VIDEODRIVER=wayland` environment variable if you want to test, SDL still defaults to X yet)

So let's give up on the Wayland part of SDL for the moment. The SDL X11 backend and SFML windows are still resizable while they should not. How can I provide more information about their X properties to try to debug the issue?

**Comment by ascent12** [comment]
Grepping through SDL's source code, they're not using `xdg_toplevel_set_(max|min)_size` anywhere.
This is how you're supposed to convey to the Wayland compositor that you're not resizable.

File an issue with them.

**Comment by markand** [comment]
Done and edited my comment. Regarding XWayland applications, how can I help debugging the issue for both SFML/SDL (with X backend) apps?

**Comment by emersion** [comment]
I think `get_constraints` is missing from the Xwayland implementation:

- xdg-shell impl: https://github.com/swaywm/sway/blob/master/sway/desktop/xdg_shell.c#L122
- Missing Xwayland impl: https://github.com/swaywm/sway/blob/master/sway/desktop/xwayland.c#L296

We should probably return the [X11 size hints](https://github.com/swaywm/sway/blob/master/sway/desktop/xwayland.c#L245) there.

**Comment by rcgordon** [comment]
> File an issue with them.

The Wayland issue has been filed with SDL:

https://bugzilla.libsdl.org/show_bug.cgi?id=4859

There's an initial SDL patch on that bug report. Thanks for bringing this to our attention! We have a long way to go on our Wayland backend, so please don't hesitate to send people to us when things like this come up.

--ryan.

**Comment by markand** [comment]
Thanks Ryan for your quick support, I'll test it in a couple of hours.

**Comment by emersion** [comment]
The Xwayland part of this issue has been fixed here by @Emantor: https://github.com/swaywm/sway/pull/4729

@rcgordon: thanks for taking care of the Wayland bug in SDL! :)

I believe this issue is now fixed, closing.

**Comment by markand** [comment]
Thanks guys for your very quick support regarding the issue, you're making sway awesome :-)

**Comment by basedtho** [comment]
this is still an issue


this 

```C++
#include <SDL2/SDL.h>

int main(int argc, char *argv[]) {
  SDL_Init(SDL_INIT_EVERYTHING);
  SDL_Window *window =
      SDL_CreateWindow("title", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                       600, 400, SDL_WINDOW_SHOWN);
  SDL_SetWindowResizable(window, SDL_FALSE);
  SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
  SDL_SetRenderDrawColor(renderer, 0, 255, 0, 255);
  SDL_RenderClear(renderer);
  SDL_RenderPresent(renderer);
  SDL_Delay(3000);
}
```

results in this

![image](https://user-images.githubusercontent.com/60894565/98938702-28542280-249d-11eb-8af1-59539e4dfee7.png)

**Comment by emersion** [comment]
Unresizable windows should show up as floating by default. If the user makes them tiling, Sway will center them. This is expected behavior.

**Comment by markand** [comment]
I think it has never been pushed into the libSDL repository because it was in test, ping @rcgordon to get info on this.

**Comment by basedtho** [comment]
the thing is, i didn't make it tiling, this is how the program starts
