### ISSUE TITLE
swaybar crashes with a segfault

### ISSUE THREAD

**Issue by houseofsuns** [swaywm/sway#5350]
On my amd64 Gentoo unstable machine I see the following crash of swaybar since today. This is a bit confusing as it worked yesterday and I did not find any relevant changes in the logs.

Other information: I'm running sway-1.4 on kernel 5.6.12 on Intel graphics.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f2a2ea in ?? () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff7f2a2ea in  () at /lib64/libc.so.6
#1  0x000055555555fb0b in ipc_get_workspaces (bar=0x555555568340 <swaybar>) at ../sway-1.4/swaybar/ipc.c:363
        ws_output = <optimized out>
        i = 0
        output = 0x5555555829b0
        len = <optimized out>
        res = 0x5555555fdde0 "[ { \"id\": 4, \"name\": \"1\", \"rect\": { \"x\": 0, \"y\": 0, \"width\": 1920, \"height\": 1200 }, \"focus\": [ 7, 61 ], \"border\": \"none\", \"current_border_width\": 0, \"layout\": \"splith\", \"orientation\": \"horizontal\", \""...
        results = 0x5555555841b0
        length = 6
        ws_json = <optimized out>
        num = 0x0
        name = 0x5555555fe7e0
        visible = 0x0
        focused = 0x5555555ff670
        out = 0x0
        urgent = 0x0
#2  0x000055555555a178 in bar_setup
    (bar=0x555555568340 <swaybar>, socket_path=0x555555579960 "/run/user/1001/sway-ipc.1001.1872.sock")
    at ../sway-1.4/swaybar/main.c:86
        registry = <optimized out>
        seat = 0x555555568068 <xdg_shell_types+72>
        socket_path = 0x555555579960 "/run/user/1001/sway-ipc.1001.1872.sock"
        debug = <optimized out>
        usage = 0x555555564148 "Usage: swaybar [options...]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -v, --version          Show the version number and quit.\n  -s, --socket <socket>  Connect to sway via socket.\n  -b, "...
        c = <optimized out>
        long_options = 
            {{name = 0x5555555639ae "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x555555563617 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5555555639b3 "socket", has_arg = 1, flag = 0x0, val = 115}, {name = 0x5555555639ba "bar_id", has_arg = 1, flag = 0x0, val = 98}, {name = 0x5555555639c1 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
#3  main (argc=<optimized out>, argv=<optimized out>) at ../sway-1.4/swaybar/main.c:90
        socket_path = 0x555555579960 "/run/user/1001/sway-ipc.1001.1872.sock"
        debug = <optimized out>
        usage = 0x555555564148 "Usage: swaybar [options...]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -v, --version          Show the version number and quit.\n  -s, --socket <socket>  Connect to sway via socket.\n  -b, "...
        c = <optimized out>
        long_options = 
            {{name = 0x5555555639ae "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x555555563617 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5555555639b3 "socket", has_arg = 1, flag = 0x0, val = 115}, {name = 0x5555555639ba "bar_id", has_arg = 1, flag = 0x0, val = 98}, {name = 0x5555555639c1 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}

**Comment by houseofsuns** [comment]
Sway log with a crashing swaybar:

[sway.log](https://github.com/swaywm/sway/files/4638364/sway.log)

**Comment by houseofsuns** [comment]
Actually looking at the next issue in the list (#5349) this may be related to json-c which I updated yesterday (from 0.14-r1 to 0.14-r2, so just a minor update on the Gentoo side, but maybe this triggered it).

**Comment by JonasToth** [comment]
I see the same issue on gentoo.

```
kernel: [ 1884.681906] swaybar[11918]: segfault at 0 ip 00007f241d826bba sp 00007fff45825e68 error 4 in libc-2.31.so[7f241d6f2000+14a000]
kernel: [ 1884.681913] Code: 80 7e 10 00 0f 84 f9 fe ff ff e9 11 f8 f4 ff 90 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 56 03 00 00 <c5> fe 6f 0f c5 f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9
```

It could be related to an update to glibc-2.31 as well. The crashes happen after I did this one.
The gentoo builds do not include debug symbols but I try to poke around a bit with a debugger. Maybe I find more information on the crash.

**Comment by JusterK** [comment]
It's an issue with json-c it has been fixed in master. Try unmasking dev-libs/json-c-9999 and recompile it and sway.

**Comment by JonasToth** [comment]
> It's an issue with json-c it has been fixed in master. Try unmasking dev-libs/json-c-9999 and recompile it and sway.

I did so, but it did not seem to fix the issue.
The crash still persists at the same location. Is there a way to check which json-c was used when compiling sway? Maybe there it was not picked up properly or something.

**Comment by houseofsuns** [comment]
> > It's an issue with json-c it has been fixed in master. Try unmasking dev-libs/json-c-9999 and recompile it and sway.
> 
> @JusterK I did so, but it did not seem to fix the issue.
> The crash still persists at the same location. 

Ditto. No change.

**Comment by JonasToth** [comment]
> > > It's an issue with json-c it has been fixed in master. Try unmasking dev-libs/json-c-9999 and recompile it and sway.
> > 
> > 
> > @JusterK I did so, but it did not seem to fix the issue.
> > The crash still persists at the same location.
> 
> Ditto. No change.

Ok. It  looks like a `NULL` passed into `strcmp` or so. Would still be interesting how this was triggered, because sway and json-c where not updated on gentoo, were they?
Whatever happened should be masked in gentoo for now.

**Comment by houseofsuns** [comment]
json-c actually was updated in Gentoo yesterday, but 0.14 is available since 2. May.

**Comment by JonasToth** [comment]
> json-c actually was updated in Gentoo yesterday, but 0.14 is available since 2. May.

My suspect update: https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-libs/json-c?id=bff018bc9e26a181b25250edd90192b22736fd02
(Here is the list of all changes lately: https://gitweb.gentoo.org/repo/gentoo.git/log/dev-libs/json-c?showmsg=1)

I dont have time to further investigate right now. Did the upstream devs fix those security issues, too?
If the patch is only within gentoo then this should be considered!

**Comment by JusterK** [comment]
@JonasToth @houseofsuns Did you rebuild sway again after building json-c and restart sway?
I waybar instead of swaybar, but when I try the latter it works as expected, too.

**Comment by yellowhat** [comment]
Hi,
I am experiencing the same error as @houseofsuns.
I have just tryied to rebuild json-c and sway but I get the same

**Comment by Xyene** [comment]
Closing as a duplicate of https://github.com/swaywm/sway/issues/5349; this needs to be fixed upstream and repackaged, there's nothing we can do on sway's end.

**Comment by houseofsuns** [comment]
The problem is not within swaybar, but the surrounding sway instance. So after rebuilding against a working json-c version the session needs to be restarted. This worked for me with json-c-0.14-r1. I assume that json-c-9999 would also have worked, but previously I just reexecuted swaybar and did not restart the entire session, so an error occurred.

**Comment by JonasToth** [comment]
> @JonasToth @houseofsuns Did you rebuild sway again after building json-c and restart sway?
> I waybar instead of swaybar, but when I try the latter it works as expected, too.

I logged out and back in, that did not work. But today with a fresh boot that bar is back!
Thanks for the help!
