### ISSUE TITLE
On screen corruption after changing WLR_DRM_DEVICES

### ISSUE THREAD

**Issue by GiantNuker** [swaywm/sway#6725]
Sway version: `1.6-17ee30d0 (Dec 20 2021, branch 'master')` (compiled from git an hour before i posted this)

[Log](https://gist.github.com/GiantNuker/e66396f7805e857d62805228642363b0) (Start sway (ulauncher), open idea, then close idea)
[Sway config](https://gist.github.com/GiantNuker/dc6a89f2d082ab26805c454fa47719f8) (basically default except waybar and keybinds)
[Sway launch script](https://gist.github.com/GiantNuker/e17a2878faf1d37a512b4773579441d0)

Hardware of interest:
- Ryzen 5800H Integrated Graphics
- Radeon RX 6700M Dedicated Graphics
- No MUX Switch
(This is a laptop)

Steps I took:
I noticed that minecraft was stuttering extremely hard at 4k, dropping to about 10 fps, even though the FPS counter was saying about 140, so I assumed the compositor was causing the lag.
Through trial and error I figured out that switching the `WLR_DRM_DEVICES` environment variable from `/dev/dri/card1:/dev/dri/card0` to `/dev/dri/card0:/dev/dri/card1` seemed to fix it somehow, while also making `DRI_PRIME` work opposite from how it should (1 = igpu 0 = dgpu).
Noticing the PRIME issue, I put `DRI_PRIME=1` into /etc/environment, and make my `dgpu` script use `DRI_PRIME=0`, then rebooted.
After I launched IDEA i noticed it doing this in the project graph:
![image](https://user-images.githubusercontent.com/43734540/146698642-4feb9a95-ef94-4872-91bb-c60ec6bf05fa.png)
(I made sure it only happened after the changes by reverting them, and also launching under xorg)
It does follow the idea window (dosen't stick on the screen when i move it) and appear only on the project graph (couldn't make it happen in any other programs either)
I also tried launching idea with both the dedicated and integrated gpu, same result

I have no idea whats causing this, or what broke my `WLR_DRM_DEVICES` variable, but it seemed like here or wlroots would be the best place to report it.

**Steps to reproduce**:
 - Set the `WLR_DRM_DEVICES` variable to `/dev/dri/card0:/dev/dri/card1` before starting sway
 - Start sway
 - Open IDEA (or any other jetbrains IDE, it happens in CLion too)
 - Look at the project graph

(I have no idea how reproduceable this bug is with different hardware configurations, and I'm reporting it here instead of to jetbrains as it only happens with sway, and only after changing `WLR_DRM_DEVICES`)

**Comment by GiantNuker** [comment]
Also happens in gimp 
![image](https://user-images.githubusercontent.com/43734540/147613820-c9629343-0659-4236-8461-b4e31808fd37.png)
![image](https://user-images.githubusercontent.com/43734540/147613828-292befcb-e2e3-4b7a-92c5-caec423d1805.png)

**Comment by xsrvmy** [comment]
Sanity check: have you checked if minecraft is using your gpu rather than llvm or something like that as the renderer?

**Comment by GiantNuker** [comment]
> Sanity check: have you checked if minecraft is using your gpu rather than llvm or something like that as the renderer?

Yes. The gimp example above is the same with nothing else open, and low cpu/gpu/ram usage. (retested)
![image](https://user-images.githubusercontent.com/43734540/150772715-050106b5-daec-4de2-81e0-99d7bbdfa4eb.png)
![image](https://user-images.githubusercontent.com/43734540/150772855-e91036b6-48a7-4a04-bcc8-103024ffb15b.png)

Note: While resizing the wl-copy window I noticed the dedicated gpu usage much higher. I'm assuming thats because swapping the gpu order makes sway use the dedicated gpu or something similar.

**Comment by bl4ckb0ne** [comment]
Could you provide a full debug log please (using `-Vd`)

**Comment by GiantNuker** [comment]
> Could you provide a full debug log please (using `-Vd`)

In which gpu configuration?

**Comment by bl4ckb0ne** [comment]
Both if possible

**Comment by GiantNuker** [comment]
Procedure:
1. run script
2. open gimp (through ulauncher)
3. click on a context menu (looks like this with card0_card1) 
![image](https://user-images.githubusercontent.com/43734540/151255518-b7e6c6d7-15ec-4fc4-b863-240c50ce3dad.png)

[sway_card0_card1.txt](https://github.com/swaywm/sway/files/7945911/sway_card0_card1.txt)
[sway_card1_card0.txt](https://github.com/swaywm/sway/files/7945912/sway_card1_card0.txt)

launch script:
```sh
#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Firefox
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1

# QT
#export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORM=xcb # fix broken context menus
export QT_QPA_PLATFORMTHEME=qt5ct

# SDL
export SDL_VIDEODRIVER=wayland

# Java
export _JAVA_AWT_WM_NONREPARENTING=1
export STUDIO_JDK=/usr/lib/jvm/java-17-openjdk
export JDK_JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"

# Multi-GPU
export WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0

# enable tearing/stop cursor stuttering under load
# export WLR_DRM_NO_ATOMIC=1

# Gnome Keyring Init
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

sway -Vd 2> sway_card1_card0.txt```

**Comment by frap129** [comment]
@bl4ckb0ne I'm getting similar corruption on my laptop with an RX 6800m, though it only happens on external displays. According to dmesg, it seems like something is triggering a bug in amdgpu. Do you have similar logs when this happens?
dmesg:

```
Jan 27 08:10:05 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:07 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:07 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:07 ArchStrix kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=39907, emitted seq=39909
Jan 27 08:10:07 ArchStrix kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process sway pid 1809 thread sway:cs0 pid 1931
Jan 27 08:10:11 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:11 ArchStrix kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP0.VGA], AE_NOT_FOUND (20210730/psargs-330)
Jan 27 08:10:11 ArchStrix kernel: ACPI Error: Aborting method \_GPE._L05 due to previous error (AE_NOT_FOUND) (20210730/psparse-531)
Jan 27 08:10:11 ArchStrix kernel: ACPI Error: AE_NOT_FOUND, while evaluating GPE method [_L05] (20210730/evgpe-511)
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Jan 27 08:10:12 ArchStrix kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed
Jan 27 08:10:12 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: [drm:amdgpu_gfx_disable_kcq [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Jan 27 08:10:12 ArchStrix kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KCQ disable failed
Jan 27 08:10:12 ArchStrix kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* failed to halt cp gfx
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d4049f680 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404a3280 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404bfb80 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404c3780 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404ceb80 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404caf80 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d40499c80 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404c7380 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404bdb80 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: amdgpu 0000:03:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x000d address=0xf7d404c1780 flags=0x0010]
Jan 27 08:10:12 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:13 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:20 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:21 ArchStrix kernel: [drm:amdgpu_dm_commit_planes [amdgpu]] *ERROR* Waiting for fences timed out!
Jan 27 08:10:21 ArchStrix kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP0.VGA], AE_NOT_FOUND (20210730/psargs-330)
Jan 27 08:10:21 ArchStrix kernel: ACPI Error: Aborting method \_GPE._L05 due to previous error (AE_NOT_FOUND) (20210730/psparse-531)
Jan 27 08:10:21 ArchStrix kernel: ACPI Error: AE_NOT_FOUND, while evaluating GPE method [_L05] (20210730/evgpe-511)
Jan 27 08:10:31 ArchStrix kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP0.VGA], AE_NOT_FOUND (20210730/psargs-330)
Jan 27 08:10:31 ArchStrix kernel: ACPI Error: Aborting method \_GPE._L05 due to previous error (AE_NOT_FOUND) (20210730/psparse-531)
Jan 27 08:10:31 ArchStrix kernel: ACPI Error: AE_NOT_FOUND, while evaluating GPE method [_L05] (20210730/evgpe-511)
Jan 27 08:10:31 ArchStrix kernel: [drm:psp_v11_0_memory_training [amdgpu]] *ERROR* send training msg failed.
Jan 27 08:10:31 ArchStrix kernel: [drm:psp_resume [amdgpu]] *ERROR* Failed to process memory training!
Jan 27 08:10:31 ArchStrix kernel: [drm:amdgpu_device_fw_loading [amdgpu]] *ERROR* resume of IP block <psp> failed -62
Jan 27 08:10:31 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:31 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
Jan 27 08:10:32 ArchStrix kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
```

**Comment by pbeliveau** [comment]
Any resolution on your end so far @frap129 ?

**Comment by frap129** [comment]
@pbeliveau Sorry for the delay, missed the notification for this. I've narrowed down my issue to being caused by [this bug in amdgpu](https://gitlab.freedesktop.org/drm/amd/-/issues/1748). It results in corruption very similar to this, but the dGPU crashes (bug during power-off, unable to resume after), so the display isn't usable after the corruption appears like the bug here.

**Comment by pbeliveau** [comment]
Did you try this mentioned temporary fix?
```amdgpu.ppfeaturemask=0xfff73fff```

I have an external 5700XT but get the exact same crash with dmesg output as you do.

**Comment by frap129** [comment]
> Did you try this mentioned temporary fix? `amdgpu.ppfeaturemask=0xfff73fff`
> 
> I have an external 5700XT but get the exact same crash with dmesg output as you do.

Yes, but since I'm on a laptop I don't use that because it breaks suspend (Disables gfxoff for the GPU, sleep is never achieved). I've been running radeontop in the background and thats worked so far for me. It destroys battery life, but the constant info polling prevents the gpu from idling, essentially disabling gfxoff while maintaining suspend

**Comment by frap129** [comment]
Reporting back that the upstream bug that was causing this issue for me has been fixed since kernel 5.18. if the original reporter is not responding, this can probably be closed

**Comment by GiantNuker** [comment]
> Reporting back that the upstream bug that was causing this issue for me has been fixed since kernel 5.18. if the original reporter is not responding, this can probably be closed

For me it still happens in gimp, but not in idea

![image](https://user-images.githubusercontent.com/43734540/179433955-577a2c31-fc02-4c14-ba4d-d2c4cff14413.png)

**Comment by pbeliveau** [comment]
Also fixed for me since 5.18
