### ISSUE TITLE
UI elements are broken for Xwayland and Java when screen is rotated

### ISSUE THREAD

**Issue by LaserEyess** [swaywm/sway#6907]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions on IRC at #sway on Libera Chat.
- Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Sway Version:**
  - `sway version 1.7`

- **Debug Log:**
 - run with `_JAVA_AWT_WM_NONREPARENTING=1 sway -d -c test.conf` https://0x0.st/oNLA.log

- **Configuration File:**
 - https://0x0.st/oNLT.conf

- **Stack Trace:**
  - N/A

- **Description:**
  - When running a java xwayland program such as pycharm on a rotated window, UI elements are not selectable. This does not happen on a non-rotated output. Unfortunately, this program is not natively wayland so I'm unable to test if this is some issue with the program only on xwayland.
  - Video on a non-rotated display 

https://user-images.githubusercontent.com/16581533/159183761-5c513d2a-b8b1-442d-a179-5e12315e09ce.mp4

 - video on a rotated display

https://user-images.githubusercontent.com/16581533/159183849-eb862b56-88df-4274-a7f6-7bc0e237dbf1.mp4

**Comment by Nefsen402** [comment]
This seems like a bug with xwayland unmanaged surfaces. Sway handles those differently from regular wayland popups or other surfaces. It's conceivable that there`s a lingering bug there. #6844 should solve this class of bug.

**Comment by LaserEyess** [comment]
That is a large PR... I'll try to test it though.

**Comment by LaserEyess** [comment]
@Nefsen402 your PR does not seem to solve this, is there any wlroots patches I need to apply? I just applied your patches on top of wlroots master and sway master.

**Comment by LaserEyess** [comment]
This is just https://github.com/swaywm/sway/wiki#mouse-events-clicking-scrolling-arent-working-on-some-of-my-workspaces apparently
