### ISSUE TITLE
Major visual glitches when fullscreening video in two-gpu amdgpu setup

### ISSUE THREAD

**Issue by sunox1** [swaywm/sway#6911]
- Sway version: 1.7
- Log: https://dpaste.com/FQCE96L2Y
- Issue exists with default config

Image showing problem: 
https://i.imgur.com/Jo68i7u.jpg

Basically, when I fullscreen a video on the screen driven by the 'secondary' gpu in a 2-gpu setup, the screen becomes full of artifacts. If I leave it fullscreened with artifacts showing, it will eventually seemingly cause my video cards to sort of 'lock up': both screens go black, the LED on my one gpu shut off, and the system seems responsive but can't soft shutdown. The problem does not happen on the screen driven by the 'primary' gpu.

The problem only happens when the cursor and/or OSD is **not** visible on that screen: if I move the cursor off the screen, or if it drops into the 'background' after a few second pause. As soon as the cursor/OSD returns, the video comes back.

Some background:

I normally sway like this:
`WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card1 dbus-run-session sway`

I believe this just forces the default behaviour of rendering video with my primary gpu, with the second gpu playing a more passive role. 

The problem applies to the 'passive' gpu. When I flip the order of those (card1 is primary; card0 secondary), the problem starts happening on card0.

My GPUs:
- AMD RX 480: AMDGPU
- AMD R9 270X: AMDGPU (also happened using Radeon)

OS:
- Gentoo 

CPU:
- Ryzen 3600

I've tested with both mpv and VLC, and both show the problem.

I only recently installed my second gpu and it started happening right away. It didn't appear with a sway version change or anything.

I am willing to provide a stack trace, but I'm not using systemd so I don't think I can follow the instructions included in the template. I'm also not sure if sway technically crashes.

**Comment by emersion** [comment]
This is likely fixed by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2f350ddadca3b96c72ed1481875f0b8fc1a01612 released in kernel 5.16.

**Comment by sunox1** [comment]
Cool, thank you!

**Comment by sunox1** [comment]
Just updating to say that I am using a new power supply and the issue persists, so we can rule that potential cause out.

**Comment by attente** [comment]
Thank you, `-Dnoscanout` worked for me as well. I only use a single AMD GPU though and my kernel version is 5.17.3.

**Comment by StaticRocket** [comment]
Also saw these artifacts in the form of banding on one of two monitors. This was without any application being fullscreen and with only waybar running. Moving the cursor was enough to agitate it. The `-Dnoscanout` option also seems to fix it. Experienced this with both the Vulkan and GLES renderers.

GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] (rev c8)
OS: Arch Linux
Kernel: 6.8.1-arch1-1
Mesa: 1:24.0.3-2
Vulkan: vulkan-radeon 1:24.0.3-2
Sway: sway version 1.9
