### ISSUE TITLE
Cursor not tracking targets correctly with fractional scaling

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#7562]
After recent commits, I'm unable to target the intended position with my cursor in the Chrome browser's tab/address bar area.

To reproduce:
1. Open chrome in Wayland mode:  google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
2. Open multiple tabs with Ctrl+t
3. Try to close one of the tabs with the mouse cursor by hitting the "x" on the tab

Even trying to click into the address bar fails. The clicks happen in areas away from the cursor.

**Comment by alejor** [comment]
Same here... this has to do with latest chrome 113 and wp-fractional new stuff with latest wlroots - sway code

**Comment by J0nnyMak0** [comment]
> Same here... this has to do with latest chrome 113 and hidpi displays, wp-fractional new stuff with latest wlroots - sway code

Yes, should have mentioned my output setting:
```
output eDP-1 pos 0 0 mode 3840x2160 scale 1.5
```

**Comment by J0nnyMak0** [comment]
wdisplays has also started to suffer from this issue. Notice how the window does not span the entire container.
![wdisplays](https://user-images.githubusercontent.com/6559121/235976039-49fa5164-c62d-4caa-983d-8971ce0a9f61.png)

**Comment by q234rty** [comment]
Pretty sure this is a chromium issue: qt 6.5 which also has wp-fractional-scale-v1 works fine, and chromium 113 is broken on kwin as well.
Also a chromium build from https://download-chromium.appspot.com/ works fine, I think this is fixed after https://chromium-review.googlesource.com/c/chromium/src/+/4370091

**Comment by claui** [comment]
I’ve been able to reproduce this issue on **non-Chromium** apps with **non-fractional** scaling.

My settings are:

```plain
output DP-1 scale 2
output DP-2 scale 2
output DP-1 pos 0 540
output DP-2 pos 48 0
```

I can also confirm that downgrading to commit 90c2d631 (and matching wlroots commit [`38839ac5`](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/38839ac536524e0bb43eaea80cf02b57463a59e3)) fixes the issue.

**Comment by q234rty** [comment]
It seems that there are two different issues going on here:

1. chromium 113.0.5672.63 is bugged with wp_fractional_scale_v1, this should be fixed on chromium 114+.
2. gtk4 apps and wdisplays are broken, which does seem to be a sway/wlroots regression, and also does not seem to require fractional scaling i.e. can be reproduced on integer scaling or even no scaling at all.

@J0nnyMak0, could you update the title to make it clear that this issue is tracking the second point above?

**Comment by claui** [comment]
@q234rty I see. Thanks for clarifying!

**Comment by q234rty** [comment]
I don't think that commit fixes gtk4-demo for example, did you test that?

**Comment by claui** [comment]
@q234rty You’re correct.  
What I actually meant (but failed to mention) is that those commits fixed target tracking for me in the apps I’m actually using, such as VS Code and kitty.  
I just tested gtk4-demo and can confirm that tracking is broken there, even with current tip-of-the-tree builds of wlroots and sway.

**Comment by alejor** [comment]
Hi, just for noting, I downgraded from wlroots-git and sway-git to archlinux community stable versions and all works fine so far. I needed to do this as sway is my main tool...

**Comment by J0nnyMak0** [comment]
I think the chrome issue is fixed with the latest update 113.0.5672.126. And wdisplays is also fixed per my last comment. I'm going to close this. But if anybody else still has issues with other apps, feel free to re-open.

**Comment by riskygit** [comment]
This is not fixed... my mouse changes size when I move it over different windows and seems to double in size when I share my screen. Chromium, for me, has its own problem where the window is zoomed in to the top left corner and the rest isn't visible.

**Comment by riskygit** [comment]
This appears to be fixed now.

**Comment by 0xdeface** [comment]
nope, 19.08.2024 and i have perioditically same issue. 2 screen 100% and 175%

**Comment by Propfend** [comment]
Im still having the same problem here on NixOS.

Edit:

In my case it wasnt working with chrome. Works when running it with `--disable-features WaylandFracionalScaleV1` besides `--ozone-plataform=wayland`
