### ISSUE TITLE
Vanishing popup in Java application (interactivebroker's trading app TWS)

### ISSUE THREAD

**Issue by martin-greentrax** [swaywm/sway#7823]
- **Sway Version:** 1.8.1

Debug log + sway config:  https://gist.github.com/martin-greentrax/99adb82ecfacc1d97519e73b39d37e3d
config is the default one with only the Mod key changed as I loaded sway inside sway

**Description:**

It is very similar to this closed issue: https://github.com/swaywm/sway/issues/4370

This identical problem exists on i3 and sway with interactivebroker's java-based trading application. Here is a screencast showing the problem: https://imgur.com/a/kosdB11

When clicking on a input field (for the limit price of an order) that at the same time offers drop-dop selection of a value, the dropdown is only visible for a fraction of a second and then disappears again. It makes the input field also lose focus, which makes it impossible to select or enter any value.
TWS shows an error dialog: **Price/Size wand may not show because it can't be opened at the edge of the screen. Please move window towards the center of your screen and try again**.  (Screenshot: https://imgur.com/a/fDQHmdG)

**What I tried:**

I have _JAVA_AWT_WM_NONREPARENTING=1 and tried various for_window rules but so far it did not have any effect.
In "swaymsg -t get_tree" this little popup shows up as:

`floating_con " " (xwayland, pid: 18934, instance:  "sun-awt-X11-XDialogPeer", class: "install4j-jclient-Launcher", X11  window: 0x10229A6)`

I had a bit of success with the button popup for the font size control, that disappeared when the mouse touched it by adding:

`for_window [class="install4j-jclient-Launcher"] sticky enable, floating enable, focus_follows_mouse no`
But it didn't help with the price input.

Also related issue descriptions: https://github.com/swaywm/sway/issues/3007 + https://www.reddit.com/r/swaywm/comments/q5uy12/intellij_popups_like_find_in_files_closing_when/

**Reproduce**

- Download and install TWS from: https://www.interactivebrokers.com/en/trading/tws-updateable-latest.php
- launch: ~/Jts/tws
- select paper trading
- click on "No username? Try the demo"
- enter any email, confirm
- close the welcome screen
- on the top left area of the screen click on LMT PRICE 0.00

**Comment by SolidTux** [comment]
I'm observing the same behaviour with Zoom popup menus.

System information:

* Fedora 39
* Sway 1.8.1
* AMD RX 6800XT
* amdgpu 23.0.0
* mesa 23.3.4

**Comment by SolidTux** [comment]
I just tried, and my problem is fixed on master, maybe yours as well?

**Comment by martin-greentrax** [comment]
Sadly no. I just tried the current master @ https://github.com/swaywm/sway/commit/7a2ff7ba810ced55297a1a2e420b0b1f4326ab72 but the issue remains.

I get log messages like these when I click on the input field:

```
00:03:29.339 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2358, value 6295496
00:03:29.339 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2359, value 6295496
00:03:29.810 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:29.810 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:29.811 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2444, value 6295553
00:03:29.811 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2445, value 6295553
00:03:31.302 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2523, value 6295626
00:03:31.302 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2524, value 6295626
00:03:31.302 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2526, value 6295626
00:03:31.302 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2527, value 6295626
00:03:32.034 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:32.034 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:32.034 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2614, value 6295686
00:03:32.034 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2615, value 6295686
00:03:32.732 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:32.732 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:32.732 [wlr] [xwayland/xwm.c:1170] Failed to get window property
00:03:33.360 [wlr] [xwayland/xwm.c:1634] xcb error: op 18:0, code 3, sequence 2780, value 6295804
00:03:33.360 [wlr] [xwayland/xwm.c:1634] xcb error: op 19:0, code 3, sequence 2781, value 6295804
```

**Comment by jdjxk** [comment]
I encountered the same issue on WeChat.

**Comment by DreamMaoMao** [comment]
i also found the issue in wechat,  hyprland and niri not this proble , all wlroot base wm own this issue, may be someting miss in wlroots.

**Comment by tokyo4j** [comment]
I think this issue has been fixed in wlroots 0.19. At least, the issue around Zoom popup menu has been fixed in labwc master, which also depends on wlroots 0.19.
